apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: milton-flows-cluster-ingress
  annotations:
    kubernetes.io/ingress.class: gce # For Google Cloud Load Balancer
    networking.gke.io/managed-certificates: projects/milton-prod-proj/global/sslCertificates/milton-flows-cluster-cert 
spec:
  rules:
  - host: make-api.getmilton.com  # Replace with your subdomain
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: flowise-service  # Replace with your service's name
            port:
              number: 80  # Replace with the port your service uses


apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: milton-flows-cluster-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: "milton-flows-cluster-ip-address"
    networking.gke.io/managed-certificates: "milton-flows-cluster-cert"
spec:
  defaultBackend:
    service:
      name: flowise-service
      port:
        number: 80
  tls:
  - hosts:
    - make-api.getmilton.com
    secretName: milton-flows-cluster-secret

